### ISSUE TITLE
Week_6_Assignment

### ISSUE THREAD

**Issue by Kaur-Navdeep** [navdeepkaurufl/Agronomic-problems#5]

**Comment by navdeepkaurufl** [comment]
Hi @brymz,
Thanks for providing detailed links for using R software. Currently, I am working with data visualization. I was able to use most of the commands for preparing graphs, except geom_smooth, geom_boxplot. I tried several ways to use them, but I
still get some errors every time. I am attaching the screenshot for the same. 
![Screen Shot 2021-09-22 at 8 11 43 PM](https://user-images.githubusercontent.com/89556057/134515023-e599707e-c4fc-4df3-85d3-c76eac9c253e.png)
<img width="1281" alt="Screen Shot 2021-09-23 at 9 30 51 AM" src="https://user-images.githubusercontent.com/89556057/134516183-ca520ddb-5bfd-4caf-9e75-65cda5568de9.png">

Also, wondering if you have looked upon my week 4 and 5 issues just because I wanted to know if I should keep this repository public.

**Comment by brymz** [comment]
Hi @navdeepkaurufl,

First of all, these challenges are normal and I'm happy to help. I would be able to be most helpful if the code file is uploaded for my review. Alternately you can copy the code and output as text into the message over a screenshot.

Best practice is to put as much information into the `ggplot(data = data_file, aes(x = list_one, y = list_two, group = list_three)`. In this case for `geom_smooth()` it looks like it's missing the `x` and `y` because they are listed for `geom_point()`. 

The boxplot looks good to me. "Warning message" functions different than "Error" in that the function still operates. Simple to say, but try to understand the details in the error and warning messages when you are thinking about troubleshooting.

**Comment by navdeepkaurufl** [comment]
Hi @brymz,
I am analyzing my data and find out that it is not normally distributed. I tried the Shapiro test and using histogram, box plot, and Q-Q plot. I am attaching the plots here. R code file named Grain_N_trial_harvest_data.R is uploaded in the repository. 
![Rplot01](https://user-images.githubusercontent.com/89556057/135656919-7e9b1dbd-6c0b-446d-aa2e-7ae9c181d1ba.png)
![Rplot02](https://user-images.githubusercontent.com/89556057/135656937-3042b56c-43b1-4f04-ab56-a661118b5975.png)
I tried to remove three outliers from the data, still, it is not normally distributed and it further created more outliers. I am wondering should I remove outliers or can work on the original data for this year and try removing outliers with two years data?

**Comment by brymz** [comment]
Hi @navdeepkaurufl ,

This is important information to interpret your analysis. You might try several transformations of the data to get a better sense of its "shape". My guess would by logorhythmic. For now, let's leave the outliers in.

I would encourage you to continue exploring the data through visualization and analysis whereby you test the assumptions of your statistics. For example, you could subject both the raw and transformed data to an ANOVA to see how the transformation affects those results. Also, consider the statistical assumptions within your varieties and treatment groups.

The code file is looking good. There is a week coming up where we go through some style guides that will prepare the code for my review.

**Comment by navdeepkaurufl** [comment]
Hi@brymz,
Thank you for your suggestion. I will try using log transformation. If that would not work I will try other transformations too. Also, I am considering varieties and treatment groups as factors. I am sorry, I could not understand what does it mean by statistical assumptions within your varieties and treatment groups.

**Comment by brymz** [comment]
> what does it mean by statistical assumptions within your varieties and treatment groups.

I mean something like:
- filter your data by variety and then by treatment
- look at each of the varieties and variety * treatment combinations to see if the shape (and therefore transformation) are consistent in those parts of the data
- determine the ability to conduct your analysis across these groupings

**Comment by navdeepkaurufl** [comment]
Hi @brymz,
 I tried log transformation and it worked. Two variables that are plant height and seed yield were not normally distributed. Now they became normally distributed using log transformation. I used Shapiro test for checking normality.

Now I am building for loop for easy data analysis and it works for every parameter except the HSD test. I have uploaded the R file named "for_loop" in the repository. 
I tried several ways from yesterday, but getting one or the other error. 
Currently, I am getting this error. 
Error in data.frame(y, trt) : 
  arguments imply differing number of rows: 5, 2

I am attaching my script here also for your reference. 
table(data1$N_rates_Kg_per_ha)
plot = list()
model1= list()
HSD = list()
Shapiro = list()
MSerror = list()
for(i in 5:ncol(data1)){
  column = names(data1[i])
  model1 = lm((data1[,i]~ data1$N_rates_Kg_per_ha*Variety + Rep), data = data1)
  anova = anova(lm((data1[,i]~ data1$N_rates_Kg_per_ha*Variety + Rep), data = data1))
  HSD = HSD.test (anova, trt = c("N_rates_Kg_per_ha","Variety"), group = TRUE, console=TRUE)
  library(agricolae)
  Shapiro = shapiro.test(model1$resid)
  print(column)
  print(anova)
  print(Shapiro)
  print(HSD)
}
Would you please guide me on how should I proceed? Thank you!

**Comment by brymz** [comment]
> Error in data.frame(y, trt) :
> arguments imply differing number of rows: 5, 2

Hi @navdeepkaurufl, This error means that you are trying to fit a data frame of a different size into another. It may be that all of your output has one structure that differs from the output that is provided by the `HSD.test()`. Can you identify specifically which line in this `for` loop results in the error?

**Comment by brymz** [comment]
>anova = anova(lm((data1[,i]~ data1$N_rates_Kg_per_haVariety + Rep), data = data1))

It may be that your ANOVA function is input incorrectly. Should it be `data1[,i]~ data1[,i]$N_rates_Kg_per_ha + data1[,i]Variety + data1[,i]Rep`?

The ANOVA function I tend to use is `aov()`. Is there a reason you nested `anova(lm())`? You may look at the outlook `str()` and `class()` for helpful information about the function output.
